### ISSUE TITLE
Disable mails to root

### ISSUE THREAD

**Issue by agaAdams** [YunoHost-Apps/archivist_ynh#37]
Hi there,

is there a way to disable the daily mails from cron to yh-root?

**Comment by maniackcrudelis** [comment]
Hi @agaAdams

you receive an email because of the execution of the [cron task](https://github.com/YunoHost-Apps/archivist_ynh/blob/master/conf/cron).
The cron copy the result of the execution into the log
`| tee -a`
To disable the mail, you can replace that part of the command by
`>>`
That way, the result of the command will go directly to the log, without being sent by email.

**Comment by agaAdams** [comment]
many thanks
